routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect("home");
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

//---------------------------------------------------------------USER SET---------------------------------------------------------------------//

Route::middleware(['auth', 'role:Masyarakat'])->prefix('masyarakat')->group(function () {
    Route::get('/home', [\App\Http\Controllers\DashboardUserController::class,'index'])->name('masyarakat.home');
    Route::get('/pengaduan',  [\App\Http\Controllers\User\UserController::class, 'pengaduan'])->name('masyarakat.pengaduan');
    Route::get('/laporan/{who?}', [\App\Http\Controllers\User\UserController::class, 'laporan'])->name('masyarakat.pengaduan.laporan');
    Route::get('/pengaduan-detail/{id_pengaduan}', [\App\Http\Controllers\User\UserController::class, 'detailPengaduan'])->name('masyarakat.pengaduan.detail');
    Route::post('/pengaduan/kirim',  [\App\Http\Controllers\User\UserController::class, 'storePengaduan'])->name('masyarakat.pengaduan.store');
    Route::put('/edituserprofile/{id}', [\App\Http\Controllers\DashboardUserController::class, 'editProfile'])->name('masyarakat.edit');
});

//--------------------------------------------------------------ADMIN SET---------------------------------------------------------------------//

Route::middleware(['auth', 'role:Administrator'])->prefix('admin')->group(function () {
    Route::get('/home', [\App\Http\Controllers\DashboardUserController::class, 'admin'])->name('admin.home');
    //Data Petugas
    Route::get('/petugas', [\App\Http\Controllers\Admin\PetugasController::class,'index'])->name('admin.petugas.index');
    Route::get('/petugas/create', [\App\Http\Controllers\Admin\PetugasController::class,'create'])->name('admin.petugas.create');
    Route::post('/petugas/store', [\App\Http\Controllers\Admin\PetugasController::class,'store'])->name('admin.petugas.store');
    Route::get('/petugas/edit/{id}', [\App\Http\Controllers\Admin\PetugasController::class,'edit'])->name('admin.petugas.edit');
    Route::put('/petugas/update/{id}', [\App\Http\Controllers\Admin\PetugasController::class,'update'])->name('admin.petugas.update');
    Route::delete('/petugas/delete/{id}', [\App\Http\Controllers\Admin\PetugasController::class,'destroy'])->name('admin.petugas.destroy');

//Data Masyarakat
    Route::resource('/masyarakat', App\Http\Controllers\Admin\MasyarakatController::class);
    // Route::get('/masyarakat', [\App\Http\Controllers\Admin\MasyarakatController::class,'index'])->name('masyarakat.index');
    // Route::get('/masyarakat/{$id}', [\App\Http\Controllers\Admin\MasyarakatController::class,'show'])->name('masyarakat.show');
    // Route::delete('/masyarakat/delete',[\App\Http\Controllers\Admin\MasyarakatController::class,'destroy'])->name('masyarakat.destroy');

    Route::get('/laporan', [\App\Http\Controllers\Admin\LaporanController::class, 'index'])->name('laporan.index');
    Route::post('/laporan-get', [\App\Http\Controllers\Admin\LaporanController::class, 'laporan'])->name('laporan.get');
    Route::post('/laporan/export', [\App\Http\Controllers\Admin\LaporanController::class, 'export'])->name('laporan.export');
    Route::put('/editprofile/{id}', [\App\Http\Controllers\Admin\DashboardController::class, 'editProfile'])->name('edit');
    Route::get('pengaduan/{status}', [\App\Http\Controllers\Admin\PengaduanController::class, 'index'])->name('pengaduan.index');
    Route::get('pengaduan/show/{id_pengaduan}', [\App\Http\Controllers\Admin\PengaduanController::class, 'show'])->name('pengaduan.show');
    Route::delete('pengaduan/delete/{id_pengaduan}', [\App\Http\Controllers\Admin\PengaduanController::class, 'destroy'])->name('pengaduan.delete');
    // Tanggapan
    Route::post('tanggapan', [\App\Http\Controllers\Admin\TanggapanController::class, 'response'])->name('tanggapan');
    // Kategori
    Route::resource('kategori', \App\Http\Controllers\Admin\KategoriController::class);
    Route::get('pengaduan/user/{id_pengaduan}', [\App\Http\Controllers\PengaduanController::class, 'show'])->name('aduan.show');
});

//------------------------------------------------------------PETUGAS SET---------------------------------------------------------------------//

Route::middleware(['auth', 'role:Petugas'])->prefix('petugas')->group(function () {
    Route::get('/home', [\App\Http\Controllers\DashboardUserController::class, 'admin'])->name('petugas.home');
    //Data Petugas
    Route::get('/petugas', [\App\Http\Controllers\Petugas\PetugasController::class,'index'])->name('petugas.petugas.index');
    Route::get('/petugas/create', [\App\Http\Controllers\Petugas\PetugasController::class,'create'])->name('petugas.petugas.create');
    Route::post('/petugas/store', [\App\Http\Controllers\Petugas\PetugasController::class,'store'])->name('petugas.petugas.store');
    Route::get('/petugas/edit/{id}', [\App\Http\Controllers\Petugas\PetugasController::class,'edit'])->name('petugas.petugas.edit');
    Route::put('/petugas/update/{id}', [\App\Http\Controllers\Petugas\PetugasController::class,'update'])->name('petugas.petugas.update');
    Route::delete('/petugas/delete/{id}', [\App\Http\Controllers\Petugas\PetugasController::class,'destroy'])->name('petugas.petugas.destroy');
    //Data Masyarakat
    Route::resource('/masyarakat', App\Http\Controllers\Admin\MasyarakatController::class)->names([
        'index' => 'petugas.masyarakat.index',
        'show' => 'petugas.masyarakat.show',
        'destroy' => 'petugas.masyarakat.destroy'
    ]);
    // Route::get('/masyarakat', [\App\Http\Controllers\Petugas\MasyarakatController::class,'destroy'])->name('petugas.masyarakat.index');
    // Route::get('/masyarakat/{$id}', [\App\Http\Controllers\Petugas\MasyarakatController::class,'show'])->name('petugas.masyarakat.show');
    // Route::delete('/masyarakat/delete',[\App\Http\Controllers\Petugas\MasyarakatController::class,'destroy'])->name('petugas.masyarakat.destroy');


    Route::get('/laporan', [\App\Http\Controllers\Petugas\LaporanController::class, 'index'])->name('petugas.laporan.index');
    Route::post('/laporan-get', [\App\Http\Controllers\Petugas\LaporanController::class, 'laporan'])->name('petugas.laporan.get');
    Route::post('/laporan/export', [\App\Http\Controllers\Petugas\LaporanController::class, 'export'])->name('petugas.laporan.export');
    Route::put('/editprofile/{id}', [\App\Http\Controllers\Petugas\DashboardController::class, 'editProfile'])->name('petugas.edit');
    //Pengaduan 
    Route::get('pengaduan/{status}', [\App\Http\Controllers\Petugas\PengaduanController::class, 'index'])->name('petugas.pengaduan.index');
    Route::get('pengaduan/show/{id_pengaduan}', [\App\Http\Controllers\Petugas\PengaduanController::class, 'show'])->name('petugas.pengaduan.show');
    Route::delete('pengaduan/delete/{id_pengaduan}', [\App\Http\Controllers\Petugas\PengaduanController::class, 'destroy'])->name('petugas.pengaduan.delete');
        
    // Tanggapan
    Route::post('tanggapan', [\App\Http\Controllers\Petugas\TanggapanController::class, 'response'])->name('petugas.tanggapan');
        
    // Kategori
    Route::get('kategori', [\App\Http\Controllers\Petugas\KategoriController::class,'index'])->name('petugas.kategori.index');
    Route::get('kategori/create', [\App\Http\Controllers\Petugas\KategoriController::class,'create'])->name('petugas.kategori.create');
    Route::post('kategori/store', [\App\Http\Controllers\Petugas\KategoriController::class,'store'])->name('petugas.kategori.store');
    Route::get('kategori/edit/{id}', [\App\Http\Controllers\Petugas\KategoriController::class,'edit'])->name('petugas.kategori.edit');
    Route::put('kategori/update', [\App\Http\Controllers\Petugas\KategoriController::class,'update'])->name('petugas.kategori.update');
    Route::delete('kategori/delete', [\App\Http\Controllers\Petugas\KategoriController::class,'destroy'])->name('petugas.kategori.delete');
    Route::get('pengaduan/user/{id_pengaduan}', [\App\Http\Controllers\PengaduanController::class, 'show'])->name('petugas.aduan.show');
    
});

//override,authenticated, redirect, route dr msing" dashboard

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;

    protected $table = 'kategori';

    protected $primaryKey = 'id_kategori';

    protected $fillable = [
        'nama_kategori'
    ];
}

app/Http/Controllers/Admin/KategoriController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Kategori;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = Kategori::orderBy('nama_kategori', 'asc')->get();

        return view('pages.admin.kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        Kategori::create($data);

        return redirect()->route('kategori.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = Kategori::find($id);
        return view('pages.admin.kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_kategori)
    {
        $data = $request->all();

        $item = Kategori::findOrFail($id_kategori);

        $item->update($data);

        return redirect()->route('kategori.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id_kategori)
    {
        if($id_kategori = 'id_kategori') {
            $id_kategori = $request->id_kategori;
        }

        $kategori = Kategori::find($id_kategori);

        $kategori->delete();

        if($request->ajax()) {
            return 'success';
        }

        return redirect()->route('kategori.index');
    }
}

app/Http/Controllers/Petugas/KategoriController.php
<?php

namespace App\Http\Controllers\Petugas;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Kategori;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = Kategori::orderBy('nama_kategori', 'asc')->get();

        return view('pages.admin.kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        Kategori::create($data);

        return redirect()->route('kategori.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = Kategori::find($id);
        return view('pages.admin.kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_kategori)
    {
        $data = $request->all();

        $item = Kategori::findOrFail($id_kategori);

        $item->update($data);

        return redirect()->route('kategori.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id_kategori)
    {
        if($id_kategori = 'id_kategori') {
            $id_kategori = $request->id_kategori;
        }

        $kategori = Kategori::find($id_kategori);

        $kategori->delete();

        if($request->ajax()) {
            return 'success';
        }

        return redirect()->route('kategori.index');
    }
}

resources/views/pages/admin/kategori/create.blade.php
@extends('layouts.admin')
@section('title', 'Tambah Kategori')


@push('addon-style')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
@endpush
@section('content')
    <!-- Header -->
    
      <div class="container-fluid p-4 py-4">
              <h2 class=" d-inline-block mb-4">Tambah Kategori</h2>
              {{-- <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Petugas</a></li>
                </ol>
              </nav> --}}
        <!-- Page content -->
        <div class="container-fluid">
            <div class="row">
              <div class="col-xl-6">
                <div class="card" style="border-radius: 1.25rem; box-shadow: 0 .1rem 1rem rgb(23,43,77,.14)">
                  <div class="card-body">
                    <form action="{{ route('kategori.store')}} " method="POST">
                    @csrf
                      <!-- Kategori -->
                      <div class="">
                        <div class="form-group">
                          <label class="form-control-label">Nama Kategori</label>
                          <input rows="4" class="form-control" name="nama_kategori" id="nama_kategori" placeholder="Ketik Nama Kategori" required>
                        </div>
                      </div>
                      <button type="submit" class="btn text-white" style="background-color: #454696;">Simpan</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
@endsection

@push('addon-script')
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#pengaduanTable').DataTable();
    } );
</script>
@if (session()->has('status'))
<script>
    Swal.fire({
        title: 'Pemberitahuan!',
        text: "{{ Session::get('status') }}",
        icon: 'success',
        confirmButtonColor: '#454696',
        confirmButtonText: 'OK',
    });
    </script>
@endif
@endpush

resources/views/pages/admin/kategori/edit.blade.php
@extends('layouts.admin')
@section('title', 'Edit Kategori')


@push('addon-style')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
@endpush
@section('content')
    <!-- Header -->
    
      <div class="container-fluid p-4 py-4">
              <h2 class=" d-inline-block mb-4">Edit Kategori</h2>
              {{-- <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Petugas</a></li>
                </ol>
              </nav> --}}
          
    
        <!-- Page content -->
        <div class="container-fluid">
            <div class="row">
              <div class="col-xl-6 order-xl-2">
                <div class="card" style="border-radius: 1.25rem; box-shadow: 0 .1rem 1rem rgb(23,43,77,.14)">
                  <div class="card-body">
                    <form action="{{ Auth::user()->role[0]->role_name == "Petugas" ? route('petugas.kategori.update') : route('kategori.update', $kategori->id_kategori)}} " method="POST">
                    @method('PUT')
                    @csrf
                      <!-- Kategori -->
                        <div class="form-group">
                          <label class="form-control-label">Nama Kategori</label>
                          <input rows="4" class="form-control" name="nama_kategori" id="nama_kategori" value="{{ $kategori->nama_kategori}}" placeholder="Ketik Nama Kategori" required>
                        </div>
                      <button type="submit" class="btn text-white" style="background-color: #454696;">Simpan</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
@endsection

@push('addon-script')
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#pengaduanTable').DataTable();
    } );
</script>
@if (session()->has('status'))
<script>
    Swal.fire({
        title: 'Pemberitahuan!',
        text: "{{ Session::get('status') }}",
        icon: 'success',
        confirmButtonColor: '#454696',
        confirmButtonText: 'OK',
    });
    </script>
@endif
@endpush

resources/views/pages/admin/kategori/index.blade.php
@extends('layouts.admin')
@section('title', 'Kategori')


@push('addon-style')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
@endpush
@section('content')
    <!-- Header -->
    
      <div class="container-fluid p-4 py-4">
          <h2 class=" d-inline-block mb-4">Kategori</h2>
              {{-- <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Petugas</a></li>
                </ol>
              </nav> --}}          
          <div class="row">
            <div class="col">
              <div class="card" style="border-radius: 1.5rem; box-shadow: 0 .1rem 1rem rgb(23,43,77,.14)">
                <!-- Card header -->
                <div class="card-header border-0 d-flex justify-content-between p-3 mr-2" style="border-radius: 1.5rem">
                  <h3 class="mb-0 d-flex align-items-center">Data Kategori</h3>
                  @if (Auth::user()->role[0]->role_name != 'Petugas')
                  <a href="{{ route('kategori.create')}}" class="btn text-white p-2" style="background-color: #454696;">
                    <i class="fas fa-plus"></i> Tambah Kategori</a>
                  @endif
                </div>
                <div class="card-body pt-0">
                <!-- Light table -->
                  <div class="table-responsive">
                    <table class="table align-items-center table-flush" id="pengaduanTable">
                      <thead class="thead-light">
                        <tr>
                          <th scope="col" class="sort" data-sort="no">No</th>
                          <th scope="col" class="sort" data-sort="name">Nama Kategori</th>
                          @if (Auth::user()->role[0]->role_name == 'Petugas')
                          <th scope="col" class="none" data-sort="none" style="text-align:center";>Aksi <br>(Hanya dapat diakses oleh admin)</th>
                          {{-- <th scope="col">Aksi (Hanya dapat diakses oleh Admin)</th> --}}
                          @elseif (Auth::user()->role[0]->role_name != 'Petugas')
                          <th scope="col" class="sort" data-sort="action">Aksi</th>
                          @endif
                        </tr>
                      </thead>
                      <tbody class="list">
                          @foreach($kategori as $k => $kat)

                          <tr>
                            <td class="budget">
                                <span class="text-sm">{{ $k += 1}}</span>
                            </td>
                            <td><span class="text-sm">{{ $kat->nama_kategori}}</span></td>
                            <td style="width: 100px;">
                                @if (Auth::user()->role[0]->role_name != 'Petugas')
                                <a href="{{ Auth::user()->role[0]->role_name == "Petugas" ? route('petugas.kategori.edit', $kat->id_kategori) : route('kategori.edit', $kat->id_kategori)}}" class="btn btn-sm text-white" style="background-color: #454696;"><i class="fas fa-pen"></i> Edit</a>
                                <a href="#" data-id_kategori="{{ $kat->id_kategori }}" class="btn btn-sm btn-danger kategoriDelete"><i class="fas fa-trash"></i> Hapus</a>
                                @endif
                            </td>
                          </tr>

                          @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
                <!-- Card footer -->
                {{-- <div class="card-footer py-4">
                  <nav aria-label="...">
                    <ul class="pagination justify-content-end mb-0">
                      <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">
                          <i class="fas fa-angle-left"></i>
                          <span class="sr-only">Previous</span>
                        </a>
                      </li>
                      <li class="page-item active">
                        <a class="page-link" href="#">1</a>
                      </li>
                      <li class="page-item">
                        <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                      </li>
                      <li class="page-item"><a class="page-link" href="#">3</a></li>
                      <li class="page-item">
                        <a class="page-link" href="#">
                          <i class="fas fa-angle-right"></i>
                          <span class="sr-only">Next</span>
                        </a>
                      </li>
                    </ul>
                  </nav>
                </div> --}}
              </div>
            </div>
          </div>
        
      </div>
@endsection

@push('addon-script')
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#pengaduanTable').DataTable();
    } );
</script>

<script>

    $(document).on('click', '#del', function(e) {
        let id = $(this).data('userId');
        console.log(id);
    });

    $(document).on('click', '.kategoriDelete', function (e) {
        e.preventDefault();
        let id_kategori = $(this).data('id_kategori');
        Swal.fire({
                title: 'Peringatan!',
                text: "Apakah Anda yakin akan menghapus kategori?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#454696',
                confirmButtonText: 'OK',
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: "DELETE",
                    url: '{{ route('kategori.destroy', 'id_kategori') }}',
                    data: {
                        "_token": "{{ csrf_token() }}",
                        "id_kategori": id_kategori,
                    },
                    success: function (response) {
                        if (response == 'success') {
                            Swal.fire({
                                title: 'Pemberitahuan!',
                                text: "Kategori berhasil dihapus!",
                                icon: 'success',
                                confirmButtonColor: '#454696',
                                confirmButtonText: 'OK',
                            }).then((result) => {
                                if (result.isConfirmed) {
                                    location.reload();
                                }else{
                                    location.reload();
                                }
                            });
                        }
                    },
                    error: function (data) {
                        Swal.fire({
                            title: 'Pemberitahuan!',
                            text: "Kategori gagal dihapus!",
                            icon: 'error',
                            confirmButtonColor: '#454696',
                            confirmButtonText: 'OK',
                        });
                    }
                });
            } else {
                Swal.fire({
                    title: 'Pemberitahuan!',
                    text: "Kategori gagal dihapus!",
                    icon: 'error',
                    confirmButtonColor: '#454696',
                    confirmButtonText: 'OK',
                });
            }
        });
    });



</script>
@endpush